DIC_TABLE_ID
DIC_TABLE_COLUMNCOUNT
DIC_TABLE_ISCOLUMNFAMILY
DIC_TABLE_COLUMNDISCOVERED
DIC_TABLE_METADATADISCOVERED
DIC_TABLE_NAME
DIC_TABLE_RECORD
DIC_TABLE_TIMESTAMP
DIC_TABLE_SCHEMA_ID


delete from DIC_INSTANCE;
delete from DIC_SCHEMA;
delete from DIC_TABLE;
delete from DIC_COLUMN;

select EMP_ID, EMP_NAME from NGARG.EMPLOYEE

10011894
DIC_INSTANCE_ID, DIC_INSTANCE_DATABASETYPE, DIC_INSTANCE_CONNECTIONNAME, DIC_INSTANCE_SYSTEMNAME

insert into NGARG.DIC_INSTANCE (DIC_INSTANCE_ID, DIC_INSTANCE_DATABASETYPE, DIC_INSTANCE_CONNECTIONNAME, DIC_INSTANCE_SYSTEMNAME, DIC_INSTANCE_INSTANCENAME, DIC_INSTANCE_PASSWORD, DIC_INSTANCE_PORTNUMBER, DIC_INSTANCE_USERNAME) values
('10018750', 'Hbase', 'nishtha@hbase', 'localhost', 'hbase', 'abc','9000','nishtha' )

insert into NGARG.DIC_SCHEMA (DIC_SCHEMA_ID, DIC_SCHEMA_NAME, DIC_SCHEMA_HBASETABLE, DIC_SCHEMA_INSTANCE_ID) values ('10018751', 'Citizens', 1, '10018750')

insert into NGARG.DIC_TABLE (DIC_TABLE_ID, DIC_TABLE_COLUMNCOUNT, DIC_TABLE_ISCOLUMNFAMILY, DIC_TABLE_METADATADISCOVERED,DIC_TABLE_COLUMNDISCOVERED, DIC_TABLE_NAME, DIC_TABLE_RECORD, DIC_TABLE_TIMESTAMP, DIC_TABLE_SCHEMA_ID) values ('10018752', 0, 1, 1,1, 'social_security_info', 0, 1, '10018751')

delete from DIC_COLUMN where DIC_COLUMN_TYPE = 'string'

insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018753', 400, 'Citizen_Name', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018754', 400, 'Social_security_no', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018755', 400, 'birthPlace', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018756', 400, 'DOB', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018757', 400, 'Citizenship', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018758', 400, 'Gender', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018759', 400, 'Mothername', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018760', 400, 'Contact_info', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018761', 400, 'Street_add', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018762', 400, 'Region', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018763', 400, 'Postal', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018764', 400, 'Ethinicity', 'string', '10018752');
insert into NGARG.DIC_COLUMN (DIC_COLUMN_ID, DIC_COLUMN_LENGTH, DIC_COLUMN_NAME, DIC_COLUMN_TYPE, DIC_COLUMN_TABLE_ID) values ('10018765', 400, 'Annual_income', 'string', '10018752');


insert into NGARG.DIC_MAPPER (DIC_MAPPER_ID, DIC_MAPPER_COLUMN1, DIC_MAPPER_COLUMN2) values ('10011899','10011891','10011897');
insert into NGARG.DIC_MAPPER (DIC_MAPPER_ID, DIC_MAPPER_COLUMN1, DIC_MAPPER_COLUMN2) values ('10011900','10011892','10011898');

select DIC_REGEX_ID,
DIC_REGEX_TYPE,
DIC_REGEX_REGULAREXP,
DIC_REGEX_LINKID,
DIC_REGEX_ORDER,
DIC_LINK_ID,
DIC_LINK_VALUE,
DIC_LINK_LINKID from NGARG.DIC_REGEX full join NGARG.DIC_LINK on DIC_LINK_LINKID = DIC_REGEX_LINKID order by DIC_REGEX_ORDER

update DIC_REGEX set DIC_REGEX_ORDER = 102 where DIC_REGEX_ID = '10010495'

delete from DIC_REGEX where DIC_REGEX_ID ='10010498'
select DIC_COLUMN_NAME from NGARG.DIC_COLUMN where DIC_COLUMN_TABLE_ID = '10011888'